version: "3"
services:
  configclient1:
    build:
      context: ./configclient1
      args:
        - JAR_FILE=./build/libs/configclient1-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
    environment:
      - CONFIG_SERVER_HOST=configserver1
      - CONFIG_SERVER_PORT=8888
    depends_on:
      - configserver1
    entrypoint: /bin/bash -c "sleep 30 && java -jar app.jar"
  configclient2:
    build:
      context: ./configclient2
      args:
        - JAR_FILE=./build/libs/configclient2-0.0.1-SNAPSHOT.jar
    ports:
      - 8081:8080
    environment:
      - CONFIG_SERVER_HOST=configserver1
      - CONFIG_SERVER_PORT=8888
    depends_on:
      - configserver1
    entrypoint: /bin/bash -c "sleep 30 && java -jar app.jar"
  configclient3:
    build:
      context: ./configclient3
      args:
        - JAR_FILE=./build/libs/configclient3-0.0.1-SNAPSHOT.jar
    ports:
      - 8082:8080
    environment:
      - CONFIG_SERVER_HOST=configserver1
      - CONFIG_SERVER_PORT=8888
    depends_on:
      - configserver1
    entrypoint: /bin/bash -c "sleep 30 && java -jar app.jar"
  configserver1:
    build:
      context: ./configserver1
      args:
        - JAR_FILE=./build/libs/configserver1-0.0.1-SNAPSHOT.jar
    ports:
      - 8888:8888
#    depends_on:
#      - rabbitmq
#  rabbitmq:
#    container_name: rabbitmq
#    image: library/rabbitmq:3.8.9
#    ports:
#    - 5672:5672
#    - 15672:15672
#    volumes:
#    - ./out/rabbitmq_data:/var/lib/rabbitmq